# BACKUP ONLY -- this file is NOT symlinked anywhere.
# The live environment is generated by home-manager:
#   - env vars:  modules/home/shell/env.nix (+ xdg.enable in dotfiles.nix)
#   - PATH:      modules/home/shell/paths.nix (home.sessionPath)
# Edit the Nix modules instead; keep this file in sync for non-Nix setups.

### XDG Base Directory ###
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

### History ###
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

### Path ###

# Local binaries
export PATH=$PATH:$HOME/.local/bin

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# Cargo
export PATH=$PATH:$HOME/.cargo/bin

# Bun
export PATH=$PATH:$HOME/.bun/bin

# Deno
export PATH=$PATH:$HOME/.deno/bin
