name: CI
on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - lib/**
      - modules/**
      - users/**
      - .github/workflows/ci.yml
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  check:
    name: check (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            system: x86_64-linux
            # macOS is disabled until marksman builds successfully on aarch64-darwin.
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13
        with:
          use-flakehub: false
      - name: Check format
        run: nix fmt -- --ci
      - name: Flake check
        run: nix flake check --system ${{ matrix.system }} --show-trace
