name: Continuous Integration of dotfiles installation

run-name: ${{ github.actor }} is testing out dotfiles installation

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Test to install dotfiles
      run: ./install.sh
