name: Continuous Integration of dotfiles installation

run-name: ${{ github.actor }} is testing out dotfiles installation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  dotfiles-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && sudo apt-get install -y curl
      - name: Test to install dotfiles
        run: ./install.sh
